version: "3.8"

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: cats_db
      POSTGRES_USER: cats_user
      POSTGRES_PASSWORD: cats_password
    ports:
      - "5432:5432"
